# -*- coding: utf-8 -*-
"""ASRfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KJO7h0r-K0zHicfAn5gXLseaJNxTIuY
"""

!pip install openai-whisper
!sudo apt-get install ffmpeg

import whisper

# Load a model (choose size)
model = whisper.load_model("small")   # try "small" first (fast + accurate enough)

from google.colab import files
uploaded = files.upload()

!unzip audios.zip -d /content/audios

dataset_folder = "/content/audios/INNOV8 3.0/INNOV8 3.0"
eval_folder = "/content/audios/INNOV8 3.0/Evaluation set/audio"
output_folder = "/content/transcripts"
import os
os.makedirs(output_folder, exist_ok=True)

def transcribe_folder(input_folder, output_folder):
    for file in os.listdir(input_folder):
        if file.lower().endswith((".mp3", ".wav")):
            audio_path = os.path.join(input_folder, file)
            print(f"🔊 Transcribing: {file}")
            result = model.transcribe(audio_path, language="en")
            out_path = os.path.join(output_folder, os.path.splitext(file)[0] + ".txt")
            with open(out_path, "w") as f:
                f.write(result["text"])

transcribe_folder(dataset_folder, output_folder)
transcribe_folder(eval_folder, output_folder)

import re

final_out = "/content/transcript.txt"

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)       # only a–z + space
    text = re.sub(r'\s+', ' ', text).strip()   # collapse spaces
    return text

with open(final_out, "w") as fout:
    for file in sorted(os.listdir(output_folder)):
        if file.endswith(".txt"):
            with open(os.path.join(output_folder, file)) as f:
                text = f.read()
            fout.write(f"{file.replace('.txt','.mp3')} : {clean_text(text)}\n")

print("✅ Final transcript.txt created at:", final_out)

import re

with open("/content/transcript.txt") as f:
    for i, line in enumerate(f.readlines()[:10]):  # check first 10 lines
        filename, text = line.split(":", 1)
        assert filename.strip().endswith(".mp3"), f"Invalid filename at line {i}"
        assert re.fullmatch(r'[a-z ]*', text.strip()), f"Invalid chars at line {i}"
print("✅ transcript.txt is clean and valid")

from google.colab import files
files.download("/content/transcript.txt")